### ISSUE TITLE
SystemJS XHR error while running application

### ISSUE THREAD

**Issue by jerno** [gizm0bill/angular2-rest-client#1]
**Description:**
Getting error when running application (with "angular2-rest-client" dependency)

> Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
> Error loading http://localhost:3000/node_modules/angular2-rest-client/index.js as "angular2-rest-client" from http://localhost:3000/app/app.service.js

**Steps To Reproduce:**
1) `npm install angular2-rest-client`
2) add it to dependencies
3) Seen an error `Error loading http://localhost:3000/node_modules/angular2-rest-client/index.js as "angular2-rest-client"`

**Comment:**
It looks like the content of `index.js` isn't a valid javascript.
Maybe it's not transpiled to JS?

`index.js` of the _v1.0.9_ is:

```
export * from './src/angular2-rest-client';  
//# sourceMappingURL=index.js.map
```

**Comment by gizm0bill** [comment]
Actually it only works if bundling with something like webpack. I'll make an umd bundle soon!
Thanks!

**Comment by gizm0bill** [comment]
I've added the UMD bundle, should work with System.js just like in the angular2 quickstart tutorial.
