### ISSUE TITLE
Still supported and Angular4

### ISSUE THREAD

**Issue by raff77** [gizm0bill/angular2-rest-client#4]
Are you still supporting this and plan to support the latest Angular 4.

I may be able to contribute. I like the pattern you are using.

**Comment by gizm0bill** [comment]
Yes of course, I'm actively using it and plan to upgrade it next week actually. 
Does it break on Angular4?
Feel free to contribute :)

**Comment by raff77** [comment]
Great stuff, I will have a look today, seems to work fine but I am probably not using it fully.

**Comment by gizm0bill** [comment]
I pushed a branch with the upgrade but I didn't get to finalize it https://github.com/gizm0bill/angular2-rest-client/tree/angular4
